# Generated by Django 2.0.2 on 2020-12-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0007_auto_20201213_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('1', 'Retirado'), ('2', 'En Inventario')], max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
