# Generated by Django 2.0.2 on 2020-12-14 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0008_auto_20201213_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='cultivo_id',
            new_name='cultivo',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='lote_id',
            new_name='lote',
        ),
    ]
