# Generated by Django 2.0.2 on 2020-12-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0012_auto_20201213_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Cultivo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='enfermedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Enfermedad'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='produ',
            field=models.IntegerField(default='0', null=True, verbose_name='Produccion'),
        ),
    ]
