# Generated by Django 2.0.2 on 2020-12-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0013_auto_20201213_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('Retirado', 'Retirado'), ('En Inventario', 'En Inventario')], max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_riego',
            field=models.CharField(choices=[('Lunes y Miercoles', 'Lunes y Miercoles'), ('Martes y Jueves', 'Martes y Jueves')], max_length=50, verbose_name='Fecha de Riego'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, verbose_name='Género'),
        ),
    ]
