# Generated by Django 2.0.2 on 2020-12-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0015_enfermedad_fertilizante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedad',
            name='estadoRegistro',
        ),
    ]
