# Generated by Django 2.2.16 on 2020-11-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('estadoRegistro', models.CharField(max_length=2, verbose_name='Estado de Registros')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estadoRegistro', models.CharField(max_length=2, verbose_name='Estado de Registros')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('beneficios', models.TextField(verbose_name='Beneficios')),
                ('estadoRegistro', models.CharField(max_length=2, verbose_name='Estado de Registros')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('estado', models.CharField(choices=[('1', 'Retirado'), ('2', 'En Inventario')], max_length=1, verbose_name='Estado')),
                ('encargado', models.CharField(max_length=200, verbose_name='Encargado')),
                ('fecha_Ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_Salida', models.DateField(verbose_name='Fecha de Salida')),
                ('estadoRegistro', models.CharField(max_length=2, verbose_name='Estado de Registros')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('area', models.IntegerField(verbose_name='Área')),
                ('fecha_riego', models.DateField(verbose_name='Fecha de Riego')),
                ('produ', models.IntegerField(verbose_name='Produccion')),
                ('estadoRegistro', models.CharField(max_length=2, verbose_name='Estado de Registros')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('horas_trabajo', models.IntegerField(verbose_name='Horas de Trabajo')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('estadoRegistro', models.CharField(max_length=2, verbose_name='Estado de Registros')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador_Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Lote')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas', models.IntegerField(verbose_name='Cajas')),
                ('kilogramos', models.IntegerField(verbose_name='KG')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('cultivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Cultivo')),
                ('lote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Lote')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad_Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Enfermedad')),
                ('lote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Lote')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad_Fertelizante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.TextField(verbose_name='Dosis')),
                ('enfermedad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Enfermedad')),
                ('fertilizante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Fertilizante')),
            ],
        ),
    ]
