# Generated by Django 2.0.2 on 2020-12-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0004_auto_20201210_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='titulo',
        ),
    ]
