# Generated by Django 2.0.2 on 2020-12-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0005_auto_20201210_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='total',
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estadoRegistro',
            field=models.CharField(max_length=2, verbose_name='Estado de Registro'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_riego',
            field=models.CharField(max_length=50, verbose_name='Fecha de Riego'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='dni',
            field=models.IntegerField(null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='horas_trabajo',
            field=models.IntegerField(null=True, verbose_name='Horas de Trabajo'),
        ),
    ]
