# Generated by Django 2.0.2 on 2020-12-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0006_auto_20201213_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha de Asistencia')),
                ('hora_entrada', models.TimeField(null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(null=True, verbose_name='Hora de Salida')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Trabajador')),
            ],
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_Ingreso',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_Salida',
            field=models.DateField(null=True, verbose_name='Fecha de Salida'),
        ),
    ]
