# Generated by Django 2.0.2 on 2020-12-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0009_auto_20201213_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Cultivo'),
        ),
        migrations.AddField(
            model_name='lote',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Enfermedad'),
        ),
    ]
