# Generated by Django 2.0.2 on 2020-12-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0010_auto_20201213_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='produ',
            field=models.IntegerField(blank=True, null=True, verbose_name='Produccion'),
        ),
    ]
