# Generated by Django 2.0.2 on 2020-12-14 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0014_auto_20201213_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='fertilizante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Fertilizante'),
        ),
    ]
