# Generated by Django 2.0.2 on 2020-12-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosoft', '0016_remove_enfermedad_estadoregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosoft.Lote'),
        ),
    ]
